# Generated by Django 3.0.2 on 2020-01-26 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=30)),
                ('from_date', models.DateField(max_length=30)),
                ('to_date', models.DateField(max_length=30)),
                ('organised_by', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Fees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.CharField(max_length=10)),
                ('student_name', models.CharField(max_length=10)),
                ('department_class', models.CharField(max_length=10)),
                ('fees_type', models.CharField(max_length=10)),
                ('amount', models.IntegerField(max_length=10)),
                ('collection_date', models.DateField(max_length=10)),
                ('payment_reference', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
                ('subject', models.CharField(max_length=10)),
                ('author_name', models.CharField(max_length=30)),
                ('publisher', models.CharField(max_length=30)),
                ('department', models.CharField(max_length=30)),
                ('asset_details', models.CharField(max_length=30)),
                ('date_added', models.DateField(auto_now=True)),
            ],
        ),
    ]
