# Generated by Django 3.0.2 on 2020-01-26 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=30)),
                ('course_code', models.CharField(max_length=30)),
                ('course_details', models.CharField(max_length=30)),
                ('course_date', models.DateField(max_length=30)),
                ('course_price', models.CharField(max_length=30)),
                ('professor_name', models.CharField(max_length=30)),
                ('maximum_students', models.IntegerField(max_length=30)),
                ('contact_number', models.CharField(max_length=12)),
            ],
        ),
    ]
