# Generated by Django 3.0.2 on 2020-01-26 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authone', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extendeduser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='extendeduser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='extendeduser',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='extendeduser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='extendeduser',
            name='phone_number',
        ),
    ]
